# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
# Mod Properties
mod_version=6.0.0
maven_group=net.rabiesland
archives_base_name=embeddedcomputer
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.160.7+26.3

cctVersion=1.120.2
yacl_version=3.9.6+26.3-fabric